name: Deploy only to DEV firebases on push
on:
  push:
    branches:
      - firebase-auto-deploy-dev
      - main
jobs:
  normal_moove_DEV:
    if: github.repository == 'LiGHT-YalEPFL/Moove-dev'
    runs-on: ubuntu-latest
    env:
      FIREBASE_PROJECT_ID: moove-7f619-dev
      # nodejs environments:
      NEXT_PUBLIC_DISPLAY_ICRC: false
      NEXT_PUBLIC_API_KEY: AIzaSyCcJ9MKGCx4foKexUfiSboON4jv5x1D_NM
      NEXT_PUBLIC_AUTH_DOMAIN: moove-7f619-dev.firebaseapp.com
      NEXT_PUBLIC_PROJECT_ID: moove-7f619-dev
      NEXT_PUBLIC_STORAGE_BUCKET: moove-7f619-dev.appspot.com
      NEXT_PUBLIC_MESSAGING_SENDER_ID: 1083282623623
      NEXT_PUBLIC_APP_ID: 1:1083282623623:web:d394b2501b73758213bc22
      NEXT_PUBLIC_MEASUREMENT_ID: G-RYMB8WVQSR

    steps:
      - uses: actions/checkout@v4

      - name: delete .env file
        run: rm -f .env && rm -f .env.local

      - name: Build the Node.js project
        run: npm ci && npm run build

      - name: npm install the functions folder
        run: cd functions && npm ci && cd ..

      - name: Deploy to Firebase Hosting, Firestore Rules, and Functions
        run: |
          npm install -g firebase-tools
          firebase --version
          firebase deploy --project ${{ env.FIREBASE_PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN }}
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks

  humanitarian_moove_DEV:
    if: github.repository == 'LiGHT-YalEPFL/Moove-dev'
    runs-on: ubuntu-latest
    env:
      FIREBASE_PROJECT_ID: humanitarian-moove-dev
      # nodejs environments:
      NEXT_PUBLIC_DISPLAY_ICRC: true
      NEXT_PUBLIC_API_KEY: AIzaSyAg1q-W4yg4E3xIAV1bpEIGQFNo5ZaN4_Q
      NEXT_PUBLIC_AUTH_DOMAIN: humanitarian-moove-dev.firebaseapp.com
      NEXT_PUBLIC_PROJECT_ID: humanitarian-moove-dev
      NEXT_PUBLIC_STORAGE_BUCKET: humanitarian-moove-dev.appspot.com
      NEXT_PUBLIC_MESSAGING_SENDER_ID: 939080809506
      NEXT_PUBLIC_APP_ID: 1:939080809506:web:02afd7025e9404d5711e7b
      NEXT_PUBLIC_MEASUREMENT_ID: G-F162WY5CQ0
    steps:
      - uses: actions/checkout@v4

      - name: delete .env file
        run: rm -f .env && rm -f .env.local

      - name: Build the Node.js project
        run: npm ci && npm run build

      - name: npm install the functions folder
        run: cd functions && npm ci && cd ..

      - name: Deploy to Firebase Hosting, Firestore Rules, and Functions
        run: |
          npm install -g firebase-tools
          firebase --version
          firebase deploy --project ${{ env.FIREBASE_PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN }}
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks