name: Deploy in PRODUCTION on push
on:
  push:
    branches:
      - main
jobs:
  normal_moove_PRODUCTION:
    if: github.repository == 'LiGHT-YalEPFL/Moove'
    runs-on: ubuntu-latest
    env:
      FIREBASE_PROJECT_ID: moove-7f619
      # nodejs environments:
      NEXT_PUBLIC_DISPLAY_ICRC: false
      NEXT_PUBLIC_API_KEY: AIzaSyCf7qcG5dMnZADqSIzakIb6ZBVZh5c55ZI
      NEXT_PUBLIC_AUTH_DOMAIN: moove-7f619.firebaseapp.com
      NEXT_PUBLIC_PROJECT_ID: moove-7f619
      NEXT_PUBLIC_STORAGE_BUCKET: moove-7f619.appspot.com
      NEXT_PUBLIC_MESSAGING_SENDER_ID: 730851867235
      NEXT_PUBLIC_APP_ID: 1:730851867235:web:9c8ca1a79aa1c0c888d656
      NEXT_PUBLIC_MEASUREMENT_ID: G-ELDD07S9W4

    steps:
      - uses: actions/checkout@v4

      - name: Exit iff the repo is not LiGHT-YalEPFL/Moove
        run: |
          if [ "${{ github.repository }}" != "LiGHT-YalEPFL/Moove" ]; then
            echo "This is not the Deployment LiGHT-YalEPFL/Moove repository. Exiting."
            exit 1
          fi

      - name: delete .env file
        run: rm -f .env && rm -f .env.local

      - name: Build the Node.js project
        run: npm ci && npm run build

      - name: npm install the functions folder
        run: cd functions && npm ci && cd ..

      - name: Deploy to Firebase Hosting, Firestore Rules, and Functions
        run: |
          npm install -g firebase-tools
          firebase --version
          firebase deploy --project ${{ env.FIREBASE_PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN_PROD }}
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks

  humanitarian_moove_PRODUCTION:
    if: github.repository == 'LiGHT-YalEPFL/Moove'
    runs-on: ubuntu-latest
    env:
      FIREBASE_PROJECT_ID: humanitarian-moove
      # nodejs environments:
      NEXT_PUBLIC_DISPLAY_ICRC: true
      NEXT_PUBLIC_API_KEY: AIzaSyDZ02tO4jAIzUt4wr3jqxDpmQzpL9GnO3E
      NEXT_PUBLIC_AUTH_DOMAIN: humanitarian-moove.firebaseapp.com
      NEXT_PUBLIC_PROJECT_ID: humanitarian-moove
      NEXT_PUBLIC_STORAGE_BUCKET: humanitarian-moove.appspot.com
      NEXT_PUBLIC_MESSAGING_SENDER_ID: 614258218208
      NEXT_PUBLIC_APP_ID: 1:614258218208:web:4517576c806dbba81d2c85
      NEXT_PUBLIC_MEASUREMENT_ID: G-NK48MJTZSX

    steps:
      - uses: actions/checkout@v4

      - name: Exit iff the repo is not LiGHT-YalEPFL/Moove
        run: |
          if [ "${{ github.repository }}" != "LiGHT-YalEPFL/Moove" ]; then
            echo "This is not the Deployment LiGHT-YalEPFL/Moove repository. Exiting."
            exit 1
          fi

      - name: delete .env file
        run: rm -f .env && rm -f .env.local

      - name: Build the Node.js project
        run: npm ci && npm run build

      - name: npm install the functions folder
        run: cd functions && npm ci && cd ..

      - name: Deploy to Firebase Hosting, Firestore Rules, and Functions
        run: |
          npm install -g firebase-tools
          firebase --version
          firebase deploy --project ${{ env.FIREBASE_PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN_PROD }}
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks